apiVersion: v1
kind: Configmap
metadata:
  name: {{ include "vpodobaika.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "vpodobaika.labels" . | nindent 4 }}
data:
  APP_PORT: '8030'
  APP_ADDRESS: '0.0.0.0'
  APP_PROCESSES: 1
  APP_THREADED: 'False'
  APP_DEBUG: 'False'
  K8S_CONF_TEST: 'CISCO SYSTEM'
